### ISSUE TITLE
[Question] Split de pagos

### ISSUE THREAD

**Issue by marcosmarp** [Uala-Developers/ualabis-nodejs#8]
Hola! Veo en la documentación que tienen integrado el concepto de integración comercial con tiendas de terceros (https://developers.ualabis.com.ar/commercial-integrations/authentication-link) donde un cliente puede cederme su token y usuario y yo puedo crear ordenes en su nombre, pero lo que no veo es si en las ordenes puedo mandar algún parametro "fee" o "marketplace_fee" para realizar un split de pagos entre mi cuenta y la suya, basicamente tomar una comisión de orden que realiza el cliente. Es esto posible? 

Gracias.

**Comment by marcosmarp** [comment]
@pablolaggerUALA hola, este repo está activo?

**Comment by pabloUALA-BIS** [comment]
Buenas tardes @marcosmarp,

El servicio de autenticación vía link es exclusivamente para facilitar la integración de credenciales en una tienda. Dicho servicio no cuenta con la posibilidad de generar un "split" de pago en donde puedas llevarte una comisión por cada orden paga. Para mas información te recomiendo comunicarte via email a developers.ualabis@uala.com.ar en donde se te podrá dar mas info al respecto.

Por otro lado el repositorio sigue activo pero no incluye este tipo de conexiones.

Cualquier otra consulta relacionada al SDK quedo a disposición.
